class OrangeHrmElements:
    user_name_text_box_XPATH = "//input[@name='username']"
    password_text_box_XPATH = "//input[@name='password']"
    login_button_XPATH = "//button[@type='submit']"
    invalid_credentials_XPATH = "//p[text() = 'Invalid credentials']"
    PIM_module_link_text = "PIM"
    new_employee_add_button_XPATH = "//button[text()=' Add ']"
    employee_first_name_XPATH = "//*[@name='firstName']"
    employee_middle_name_XPATH = "//*[@name='middleName']"
    employee_last_name_XPATH = "//*[@name='lastName']"
    save_button_XPATH = "//button[@type='submit']"
    employee_list_XPATH = "//a[contains(text(),'Employee List')]"
    employee_id_XPATH ="//label[contains(text(),'Employee Id')]/parent::div/following-sibling::div/input"
    employee_search_button_XPATH = "//button[@type='submit']"
    driver_license_no_XPATH ="//label[contains(text(),'License Number')]/parent::div/following-sibling::div/input"
    license_expiry_XPATH ="//label[contains(text(),'License Expiry Date')]/parent::div/following-sibling::div//div/div/input "
    gender_male_XPATH = "//input[@value='1']/following-sibling::span"
    gender_female_XPATH ="//input[@value='2']/following-sibling::span"
    employee_edit_button = "//i[@class='oxd-icon bi-pencil-fill']"
    employee_delete_button = "//i[@class='oxd-icon bi-trash']"
    yes_delete_button_XPATH = "//button[@class='oxd-button oxd-button--medium oxd-button--label-danger orangehrm-button-margin']"
    nationality_button_XPATH = "//label[text()='Nationality']/../following-sibling::div/div//following-sibling::div"
    nationality_text_XPATH = "//label[text()='Nationality']/../following-sibling::div/div/div/div[@class ='oxd-select-text-input']"
    nationality_list = "//div[@role='option']"
    employee_image_XPATH = "//img[@class = 'employee-image']"
    employee_image_upload_button_XPATH = "//button[contains(@class,'employee-image-action')]"
    dashboard_text_XPATH = "//h6[text()='Dashboard']"
    home_page_search_text_box_XPATH = "//input[@placeholder='Search']"
    admin_module_XPATH = "//span[text()='Admin']"
    user_management_navigation_XPATH = "//span[contains(text(),'User Management')]"
    users_XPATH = "//a[text()='Users']"
    user_role_dropdown_button_XPATH = "//label[text()='User Role']/../following-sibling::div/div/div/*/*"
    user_role_dropdown_list_XPATH = "//div[@role='option']"
    status_dropdown_button_XPATH = "//label[text()='Status']/../following-sibling::div/div/div/*/*"
    status_dropdown_list_XPATH = "//div[@role='option']"
    SSN_number_XPATH = "//label[text()='SSN Number']/../following-sibling::div/input"
    SIN_number_XPATH = "//label[text()='SIN Number']/../following-sibling::div/input"
    marital_status_button_XPATH = "//label[text()='Marital Status']/../following-sibling::div/div//following-sibling::div"
    marital_status_text_XPATH = "//label[text()='Marital Status']/../following-sibling::div/div/div/div[@class ='oxd-select-text-input']"
    marital_status_list = "//div[@role='option']"
    date_of_brith = "//label[contains(text(),'Date of Birth')]/parent::div/following-sibling::div//div/div/input "
    employee_full_name_XPATH = "//label[text()='Employee Name']/../following-sibling::div/div/div/input"
    employee_list_present_elements_XPATH = "//div[@role='tab']/a"
    blood_type_button_XPATH = "//label[text()='Blood Type']/../following-sibling::div/div//following-sibling::div"
    blood_type_XPATH = "//label[text()='Blood Type']/../following-sibling::div/div/div/div[@class ='oxd-select-text-input']"
    blood_type_list_XPATH = "//div[@role='option']"
    edit_save_button = "//label[text()='Blood Type']/../../../../../following-sibling::div/button"
    employee_contact_details_tap_XPATH = "//a[text()='Contact Details']"
    street_1_input_box_XPATH = "//label[text()='Street 1']/../following-sibling::div/input"
    city_input_box_XPATH = "//label[text()='City']/../following-sibling::div/input"
    state_province_input_box_XPATH = "//label[text()='State/Province']/../following-sibling::div/input"
    zip_code_input_box_XPATH = "//label[text()='Zip/Postal Code']/../following-sibling::div/input"
    country_button_XPATH = "//label[text()='Country']/../following-sibling::div/div//following-sibling::div"
    country_type_list_XPATH = "//div[@role='option']"
    home_phone_no_XPATH = "//label[text()='Home']/../following-sibling::div/input"
    mobile_no_XPATH = "//label[text()='Mobile']/../following-sibling::div/input"
    work_phone_no_XPATH = "//label[text()='Work']/../following-sibling::div/input"
    work_email_id_XPATH = "//label[text()='Work Email']/../following-sibling::div/input"










